// This file was automatically generated by braintrust pull. You can
// generate it again by running:
//  $ braintrust pull --project-name "Unreleased"
// Feel free to edit this file manually, but once you do, you should make sure to
// sync your changes with Braintrust by running:
//  $ braintrust push "braintrust/unreleased.ts"

import braintrust from "braintrust";

const project = braintrust.projects.create({
  name: "Unreleased",
});

export const generateChangelog = project.prompts.create({
  name: "Generate changelog",
  slug: "generate-changelog",
  description: "Generate a changelog from a list of unreleased commits",
  model: "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
  messages: [
    {
      content:
        "Summarize the following commits from {{url}} since {{since}} in changelog form. Include a summary of changes at the top since the provided date, followed by individual pull requests (be concise).\n" +
        "\n" +
        "{{commits}}",
      role: "user",
    },
  ],
});

export const myNewPrompt = project.prompts.create({
  name: "My new prompt",
  slug: "my-new-prompt",
  model: "gpt-4o",
  messages: [{ content: "What is 1+1", role: "system" }],
});
